#!/usr/bin/env ruby
#^syntax detection
source 'https://api.berkshelf.com'

cookbook 'yum-epel', '~> 0.6.5'
cookbook 'yum-ius', '~> 0.4.5'
cookbook 'yum-webtatic', '~> 0.4.0'
cookbook 'mysql', '~> 4.0.20'
cookbook 'php', '~> 1.3.12'
cookbook 'nginx', '2.4.2'
cookbook 'data-bag-merge', '~> 0.2.4'
cookbook 'redisio', '~> 2.3.0'
cookbook 'memcached', '~> 1.8.0'
cookbook 'composer', '~> 2.2.1'
cookbook 'chef-solo-search', :github => 'edelight/chef-solo-search', :tag => 'v0.5.2'
cookbook 'nodejs', :github => 'redguide/nodejs', :tag => 'v2.4.4'

cookbook 'config-driven-helper', '~> 1.5.0'
cookbook 'php-fpm', :github => 'inviqa/cookbook-php-fpm', :tag => '0.6.11'


cookbook 'magento2', :path => 'site-cookbooks/magento2'
cookbook 'project', :path => 'site-cookbooks/project'
cookbook 'tools', :path => 'site-cookbooks/tools'
