#!/usr/bin/env ruby
# ^ Syntax hint
require 'ffi'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

# Hobo.vagrant_plugin "vagrant-hostsupdater"
# Hobo.vagrant_plugin "vagrant-omnibus"
# Hobo.vagrant_plugin "vagrant-cachier"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # vagrant-hostsupdater settings
  config.vm.hostname = "magento2training.dev"
  # config.hostsupdater.aliases = []

  # vagrant-omnibus settings
  config.omnibus.chef_version = '12.6.0'

  # vagrant-cachier settings
  config.cache.auto_detect = true

  # Box configuration
  config.vm.box = 'inviqa/centos-6-stack-php56'
  config.vm.box_version = '~> 0.3'

  # Virtualbox specific configuration
  config.vm.provider :virtualbox do |vb, overrides|
    #vb.gui = true
    vb.customize [
      "modifyvm", :id,
      "--memory", "1024",
      "--name", "magento2training"
    ]

    # Network configuration
    overrides.vm.network :private_network, ip: "10.10.186.81", netmask: "255.255.0.0"
    overrides.ssh.forward_agent = true

    # Shared folders
    mount_options = ["dmode=777", "fmode=777"]
    opts = if FFI::Platform::IS_WINDOWS
      { :mount_options => mount_options }
    elsif FFI::Platform::IS_LINUX
      { :nfs => mount_options, :nfs_version => 4, :nfs_udp => false }
    else
      { :nfs => mount_options }
    end

    overrides.vm.synced_folder(
      "../../",
      "/vagrant",
      opts
    )
  end

  config.vm.provision :chef_solo do |chef|
    # Do not add site-cookbooks to this
    # Berkshelf will copy any site-cookbooks defined in the Berksfile
    chef.cookbooks_path = "../chef/cookbooks"
    chef.environments_path = "../chef/environments"
    chef.roles_path = "../chef/roles"
    chef.data_bags_path = "../chef/data_bags"

    # Please do not add additional recipes / roles / configuration for chef in the Vagrantfile
    # If you wish to customize the VM chef config, see tools/chef/nodes/development.local.json
    chef.environment = "development"

    # Utilize config from tools/chef/nodes so it is all in one place
    require 'json'
    node_file = Pathname(__FILE__).dirname.join("..", "chef", "nodes", "development.local.json")
    if File.exists? node_file
      chef.json = JSON.load(node_file)
      chef.json['run_list'].each do |recipe|
        if recipe =~ /(.*)\[(.*)\]/
          chef.send "add_" + $1, $2
        else
          chef.add_recipe recipe
        end
      end

      if chef.json['environment']
        chef.environment = chef.json['environment']

        unless chef.environment == 'development'
          chef.encrypted_data_bag_secret_key_path = "../chef/encrypted_data_bag_secret"
        end
      end
    end
  end
end
